apiVersion: v2
annotations:
  artifacthub.io/license: MIT License
  artifacthub.io/changes: |
    - Change docs
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/rclone/rclone/blob/master/docs/content/docs.md
name: rclone
description: A Helm chart for backup persistent in gdrive
type: application
version: 0.1.4
appVersion: 1.52.3
maintainers:
- email: ymrs@yandex.ru
  name: ymrsmns
home: https://github.com/ymrsmns/helm-charts/tree/main/charts/rclone  
icon: https://rclone.org/img/logo_on_dark__horizontal_color.svg
sources:
- https://rclone.org/
- https://github.com/rclone/rclone
