apiVersion: v1
appVersion: "v0.2.1"
description: A Helm chart for version-checker
home: https://github.com/jetstack/version-checker
name: version-checker
maintainers:
  - name: ymrsmns
sources:
  - https://github.com/ymrsmns/helm-charts-0  
version: 0.0.1
